### ISSUE TITLE
Deprecated save-state

### ISSUE THREAD

**Issue by rubendinho** [JarvusInnovations/background-action#149]
Hi - this is a great action and exactly what I'm looking for. 

I did notice the below warnings when running the action: 

```
Warning: The `save-state` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

**Comment by jmealo** [comment]
@rubendinho: Thanks for your report. I haven't tested this action in going on 3 years. If it's still working for you other than this and our build process is working I'd be happy to fix this issue. We'd also be happy to accept a pull request if you have one.

**Comment by rubendinho** [comment]
> 

Hey @jmealo thanks so much - yes it's currently working great to launch a NextJS app that our Rails app needs for some tests, but outputing a lot of deprecation warnings.  Candidly I don't have much experience building/testing actions to submit a functional PR here.

**Comment by rubendinho** [comment]
> @rubendinho: Thanks for your report. I haven't tested this action in going on 3 years. If it's still working for you other than this and our build process is working I'd be happy to fix this issue. We'd also be happy to accept a pull request if you have one.

Hey @jmealo thanks so much - yes it's currently working great to launch a NextJS app that our Rails app needs for some tests, but outputing a lot of deprecation warnings. Candidly I don't have much experience building/testing actions to submit a functional PR here.

**Comment by jmealo** [comment]
That's great! I'll take a look this weekend or later tonight. I'll ping you if we publish a new version.

**Comment by jmealo** [comment]
Thank you. I started on this but didn't have time to fix the tests, they were very implementation specific. Do they pass on your branch?

**Comment by rmichalak** [comment]
Yeah, with a little hack. I explained it in the commit message.

**Comment by jmealo** [comment]
@rmichalak: Did you open a PR? I don't see it 🤔

**Comment by rmichalak** [comment]
@jmealo I only opened a PR in my fork: https://github.com/rmichalak/background-action/pull/1
It currently contains `dist` folder for my own testing and I'm pretty sure I will need to remove it if I want to open a PR to your repo.

**Comment by jmealo** [comment]
I'll be happy to clean it up. I appreciate you sharing.

**Comment by rmichalak** [comment]
I linked my PR above ⬆️ . Let me know if you need any help.
