### ISSUE TITLE
Deprecation Warnings for Node 16

### ISSUE THREAD

**Issue by Multimo** [JarvusInnovations/background-action#185]
Hello 👋 

Thanks for your work on this plugin, super useful! 

However, we have started to receive deprecation warnings from github actions for node v16. I have a PR that hopefully helps with the upgrade https://github.com/JarvusInnovations/background-action/pull/184 .

I am new to actions so not sure if there is more that is necessary here. 

https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/#:~:text=Node%2016%20has%20reached%20its,before%20finalizing%20the%20transition%20date.

<img width="1115" alt="image" src="https://github.com/JarvusInnovations/background-action/assets/6132021/39551201-814e-4dfa-9960-790456028b24">

**Comment by jmealo** [comment]
@Multimo: I'm coordinating with @themightychris, if he signs off on the Node 20 upgrade we should be good to merge your fix.

**Comment by themightychris** [comment]
Fixed in #184
